### ISSUE TITLE
Disable BOINC generation in OneClick

### ISSUE THREAD

**Issue by xtracko** [crocs-muni/oneclick#1]
Script generation is currently useless and it requires dependencies on default script files. Since we don't use it, please comment out these parts (which should alleviate the dependencies).

**Comment by mukrop** [comment]
Knock, knock, I just wanted to submit this issue because we have run into it multiple times again. What's the progress?

**Comment by LuboO** [comment]
I will solve the issue in the upcoming week, it is on my TODO list :)

**Comment by LuboO** [comment]
Solved in 8d24b4df866219829b17aff03556c2b7503ea7c1
