### ISSUE TITLE
Unify the terminology

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/oneclick#10]
There are multiple experiments (each algorithm/round setting is a different experiments), experiments are divided into Metacentrum jobs ('job' is only used with respect to Metacentrum), each job has multiple runs (running the binary).

Change at least these:
- In processed_results file it's not 1000 jobs, it's 1000 runs.
- In log output it's an experiment, not a batch (we don't use the name batch for anything now).

I know this seems just useless criticism, but the wrong usage of terms confuse new team members (true story).

**Comment by LuboO** [comment]
Solved in 30504a6bcb1b07d94f3875d4a219f41191bcaad1.
