### ISSUE TITLE
Reformat Wiki Home

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/oneclick#4]
Make a clear opening in the front document stating what the tool is and its basic motivation. At the end, add authors and affiliation (see EACirc).

**Comment by LuboO** [comment]
Done.

**Comment by mukrop** [comment]
I think it's sufficient to list you as the only author of Oneclick, since that is a practical reality. Though, you can link to the EACirc repo for other contributors for the framework if you find it appropriate.
