### ISSUE TITLE
Inform others about the changes

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/oneclick#7]
Especially anyone, who may want to use OneClick for their computations.

**Comment by xtracko** [comment]
Announcement will be done on Monday on our meeting.

**Comment by mukrop** [comment]
Ok, though email with basic instructions may be nice. Furthermore, there may only be a subgroup of us on Monday (Petr didn't announce this yet, but he will soon).

**Comment by mukrop** [comment]
Irrelevant now.
